### ISSUE TITLE
Restreamer-UI forces creation of admin user even if already exist

### ISSUE THREAD

**Issue by royvandongen** [datarhei/restreamer-ui#13]
When starting the Restreamer-UI container and opening the GUI, i need to change the admin credentials of the Restreamer-Core. These credentials are already set while booting the core(docker-compose file). 

Changing the credentials in the Restreamer-UI allows the ui to proceed to the login prompt. In this login prompt the newly "changed" credentials are not working. The Restreamer-Core credentials as specified on boot do still work.

Maybe try to make a toggle, or change the way the UI connects to the core to bypass the creation of a (non-working) admin user.

**Comment by ioppermann** [comment]
If the username and/or password are provided as environment variable, the respective fields ind the user registration dialog will be disabled. This dialog appears because `CORE_API_AUTH_ENABLE` is not set to `true`.

In order to avoid this dialog at all (and to avoid a restart of the Core), also add `- CORE_API_AUTH_ENABLE=true` to the environments in your docker-compose file.

**Comment by royvandongen** [comment]
This seems to work, thanks. Please document the environment variables if possible. and as a feature request; Maybe the ability to enter a default backendserver / list of backend servers.

**Comment by ioppermann** [comment]
The environment variables are documented in our docs at https://docs.datarhei.com/restreamer/api/environment-variables or in the README of the Core at https://github.com/datarhei/core

The default backend server is the same as where the UI is loaded from. In order to provide a different backend server add the query parameter `address` to the UI path, e.g. `http://127.0.0.1:3000/?address=http://127.0.0.1:8080` where `http://127.0.0.1:3000` is the UI and `http://127.0.0.1:8080` is the address of a backend (Core).
